package com.transport.tms.mapper;

import com.transport.tms.dto.input.CreateShipmentInput;
import com.transport.tms.dto.input.UpdateShipmentInput;
import com.transport.tms.model.Shipment;
import com.transport.tms.model.ShipmentStatus;
import org.mapstruct.*;

@Mapper(componentModel = "spring")
public interface ShipmentMapper {

    /**
     * Map CreateShipmentInput to Shipment entity
     */
    @Mapping(target = "id", ignore = true)
    @Mapping(target = "trackingNumber", ignore = true) // Generated by @PrePersist
    @Mapping(target = "status", constant = "PENDING")
    @Mapping(target = "actualRate", ignore = true)
    @Mapping(target = "deliveryDate", ignore = true)
    @Mapping(target = "createdById", ignore = true) // Set in service layer
    @Mapping(target = "createdBy", ignore = true)
    @Mapping(target = "driverId", ignore = true)
    @Mapping(target = "driver", ignore = true)
    @Mapping(target = "createdAt", ignore = true)
    @Mapping(target = "updatedAt", ignore = true)
    Shipment toEntity(CreateShipmentInput input);

    /**
     * Update existing Shipment entity from UpdateShipmentInput
     * Only updates non-null fields
     */
    @Mapping(target = "id", ignore = true)
    @Mapping(target = "trackingNumber", ignore = true)
    @Mapping(target = "shipperName", ignore = true)
    @Mapping(target = "shipperPhone", ignore = true)
    @Mapping(target = "shipperEmail", ignore = true)
    @Mapping(target = "shipperAddress", ignore = true)
    @Mapping(target = "shipperCity", ignore = true)
    @Mapping(target = "shipperState", ignore = true)
    @Mapping(target = "shipperZip", ignore = true)
    @Mapping(target = "consigneeName", ignore = true)
    @Mapping(target = "consigneePhone", ignore = true)
    @Mapping(target = "consigneeEmail", ignore = true)
    @Mapping(target = "consigneeAddress", ignore = true)
    @Mapping(target = "consigneeCity", ignore = true)
    @Mapping(target = "consigneeState", ignore = true)
    @Mapping(target = "consigneeZip", ignore = true)
    @Mapping(target = "cargoDescription", ignore = true)
    @Mapping(target = "weight", ignore = true)
    @Mapping(target = "dimensions", ignore = true)
    @Mapping(target = "vehicleType", ignore = true)
    @Mapping(target = "estimatedRate", ignore = true)
    @Mapping(target = "currency", ignore = true)
    @Mapping(target = "pickupDate", ignore = true)
    @Mapping(target = "estimatedDelivery", ignore = true)
    @Mapping(target = "createdById", ignore = true)
    @Mapping(target = "createdBy", ignore = true)
    @Mapping(target = "driverId", ignore = true)
    @Mapping(target = "driver", ignore = true)
    @Mapping(target = "createdAt", ignore = true)
    @Mapping(target = "updatedAt", ignore = true)
    @BeanMapping(nullValuePropertyMappingStrategy = NullValuePropertyMappingStrategy.IGNORE)
    void updateEntityFromInput(UpdateShipmentInput input, @MappingTarget Shipment shipment);
}
